apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness-http
  name: liveness-http
spec:
  containers:
  - image: k8s.gcr.io/liveness
    name: liveness-http
    args: ["/server"]
    resources: {}
    livenessProbe:
      httpGet: 
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
